import { useEffect } from "react";
import Head from "next/head";

import { createWorker } from "tesseract.js";

export default function Home() {
  useEffect(() => {
    const worker = createWorker({
      logger: (m) => console.log(m),
    });

    (async () => {
      await worker.load();
      await worker.loadLanguage("eng");
      await worker.initialize("eng");
      const {
        data: { text },
      } = await worker.recognize(
        "https://tesseract.projectnaptha.com/img/eng_bw.png"
      );
      console.log(text);
      await worker.terminate();
    })();
  }, []);

  return (
    <div>
      <Head>
        <title>Tesseract Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-7xl mx-auto py-12">
        <h1 className="text-xl">Tesseract Test</h1>
      </main>
    </div>
  );
}
